from ..colors import Bcolors


class VAConfigs:
    color = Bcolors

    def __init__(self):
        pass

    NESSUS_HEADERS = [
        "CVE",
        "Risk",
        "Host",
        "Protocol",
        "Port",
        "Name",
        "Synopsis",
        "Description",
        "Solution",
        "See Also",
        "Plugin Output",
    ]
    SUMMARY_SHEET_HEADERS = [
        "S.No",
        "Observation",
        "Description",
        "Impact",
        "Risk Rating",
        "Recommendation",
        "Affected Hosts",
        "Management Response",
    ]

    RAPID7_HEADERS = [
        "Vulnerability Title",
        "Asset Names",
        "Custom Tag",
        "Asset IP Address",
        "Asset Alternate IPv4 Addresses",
        "Asset OS Name",
        "Asset OS Family",
        "Service Name",
        "Asset OS Version",
        "Service Port",
        "Vulnerability Description",
        "Vulnerability CVE IDs",
        "Vulnerability CVSS Score",
        "Vulnerability Solution",
        "Exploit Count",
        "Exploit URLs",
        "Malware Kit Count",
        "Exploit Minimum Skill",
        "Asset Risk Score",
        "Asset MAC Addresses",
        "Vulnerability Severity Level",
        "Vulnerability CVE URLs",
        "Vulnerability Risk Score",
        "Vulnerability PCI Compliance Status",
        "Vulnerable Since",
    ]

    column_mismatch_error = (
        f"{Bcolors.FAIL}{Bcolors.BOLD}[!]Column mismatch between files. "
        f" Ensure all files have the same number of columns {Bcolors.ENDC}"
    )

    NESSUS_VULN_CATEGORIES = {
        "SSL Misconfigurations": "ssl_condition",
        "Missing Patches": "missing_patch_condition",
        "Unsupported Software": "unsupported_software_condition",
        "Kaspersky": "kaspersky_condition",
        "Insecure Service": "insecure_condition",
        "Winverify": "winverify_condition",
        "Unquoted Service Path": "unquoted_condition",
        "SMB Issues": "smb_condition",
        "Windows Speculative": "speculative_condition",
        "Active Directory": "AD_condition",
        "Windows Defender": "defender_condition",
        "RDP Misconfig": "rdp_condition",
        "SSH Misconfig": "ssh_condition",
        "Telnet": "telnet_condition",
        "Remote Code Execution": "rce_condition",
        "Information Disclosure": "information_condition",
        "Web Application Issues": "web_condition",
        "Windows Update Reboot": "reboot_condition",
        "Compliance": "compliance_condition",
    }
    RAPID7_VULN_CATEGORIES = {
        "SSL Misconfigurations": "ssl_condition",
        "Missing Patches": "missing_patch_condition",
        "Unsupported Software": "unsupported_software_condition",
        "SSH Misconfig": "ssh_condition",
        "Database Misconfigurations": "database_condition",
        "Web Application Issues": "web_condition",
        "Compliance": "compliance_condition",
    }
    SCAN_FILE_FORMAT = ("csv", "xlsx", "both")
    SSL_FILTER_STRINGS = "SSL|TLS|POODLE|Diffie-Hellman"
    PATCH_FILTER_STRINGS = (
        "[Pp]atch(?:es)|[Uu]pdat(?:e|es|ing)|[Ss]ecurity|Microsoft has released|"
        "JDK [Uu]pdate|JRE [Uu]pdate|Java [Uu]pdate|[Uu]pdate \\d+"
    )
    UPGRADE_FILTER_STRINGS = (
        "no longer supported|[Uu]nsupported|Obsolete Version|"
        "end-of-life|[Uu]pgrad(?:e|ing)|discontinued|later"
    )
    REBOOT_FILTER_STRINGS = "[rR]eboot"
    RDP_FILTER_STRINGS = "Terminal Services|Remote Desktop Protocol"
    WEB_FILTER_STRINGS = "Web|web server|HTTP|HSTS|HTTPS|IIS|ASP.NET"
    UNIVERSAL_IGNORE_FILTER = "[Uu]pgrade|[Uu]pdate|[Pp]atch"
    WEB_IGNORE_FILTER = "TLS|SSL"
    RISK_RATING_STRINGS = "Critical|High|Medium"
    COMPLIANCE_STRINGS = "FAILED|WARNING|Fail"
    RCE_STRING = "remote code execution"
    PATCH_OR_UPGRADE = "Update|Upgrade"

    # Scanner-specific column mappings
    COLUMNS = {
        'nessus': {
            'title': 'Name',
            'solution': 'Solution',
            'description': 'Description',
            'synopsis': 'Synopsis',
            'risk': 'Risk'
        },
        'rapid': {
            'title': 'Vulnerability Title',
            'solution': 'Vulnerability Solution',
            'service': 'Service Name',
            'pci_status': 'Vulnerability PCI Compliance Status'
        }
    }
    HEADLINE = f"\n{color.HEADER}[*]INFO[*]{color.ENDC}\n"
    VULNERABILITY_HELPER_STRING = f"""{HEADLINE}
    Runs Vulnerability analysis on 1 or multiple scans generated by Nessus or Rapid7

    Ensure the scan results have {color.BOLD}all column headers of equal number{color.ENDC} to avoid
    errors.
    For Nessus, the scan filters out only {color.UNDERLINE}{color.BOLD}Credentialed{color.ENDC} scans
    
    {color.OKCYAN}{color.UNDERLINE}required arguments{color.ENDC}:

            {color.OKGREEN}scan_folder{color.ENDC}      File Path to your scan results
            {color.OKGREEN}scanner{color.ENDC}          The scanner used [ {color.WARNING}Nessus | Rapid7{color.ENDC} ]
            {color.OKGREEN}file_type{color.ENDC}        The output filetype [ {color.WARNING}CSV | XLSX | Both
            {color.ENDC} ]
            {color.OKGREEN}filename{color.ENDC}         The name of your output file

    {color.OKCYAN}{color.UNDERLINE}return {color.ENDC}:
            {color.OKGREEN}filtered_list{color.ENDC}    Output file with the filtered vulnerabilities
            {color.OKGREEN}unfiltered_list{color.ENDC}  File containing list of all vulnerabilities that
                              were not analyzed, for manual input
{HEADLINE}"""
